version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  staticcheck:
    checks:
      - "all"
      - "-SA1012"  # Allow nil context (legacy code)
      - "-SA9003"  # Allow empty branches

issues:
  exclude-rules:
    # Exclude unused save functions in memory package
    - path: internal/memory/
      linters:
        - unused
      text: "save"
