version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks:
        - "all"
        - "-SA1012"  # Allow nil context (legacy code)
        - "-SA9003"  # Allow empty branches
        - "-ST1000"  # Package comment
        - "-ST1003"  # Variable naming
        - "-ST1020"  # Comment format
        - "-ST1021"  # Comment format
  exclusions:
    rules:
      # Exclude unused save functions in memory package
      - path: internal/memory/
        linters:
          - unused
        text: "save"
